### ISSUE TITLE
Can not download properly

### ISSUE THREAD

**Issue by 3sglue** [KirillTregubov/OverBuddy#7]
![image](https://github.com/KirillTregubov/OverBuddy/assets/172946665/d19f70cb-5112-480c-a2e1-7c7ebffc6202)

**Comment by KirillTregubov** [comment]
I'm sorry you ran into this! It seems your installation ran into an error while installing Microsoft's WebView2, which is needed to run this app.

If you are still interested in trying OverBuddy, you can try installing it directly from Microsoft at [https://go.microsoft.com/fwlink/p/?LinkId=2124703](https://go.microsoft.com/fwlink/p/?LinkId=2124703), then re-installing the [latest version of OverBuddy](https://github.com/KirillTregubov/OverBuddy/releases/latest).

Let me know if this solved your issue!

**Comment by smellysock69** [comment]
![image_2024-06-30_175242925](https://github.com/KirillTregubov/OverBuddy/assets/174281697/644a4ca3-1692-475e-b871-fb49de3a08a4)
im having the same issue

**Comment by KirillTregubov** [comment]
I'm sorry you're still running into this issue! I will look into adding a portable version of the app that doesn't require the installer.

If you're comfortable with running commands, you can help debug by sharing a log. This will help me diagnose the issue further. 
Please run the following command inside your Downloads folder (or wherever the installer is located), making sure the installer filename matches:
```cmd
msiexec /i "OverBuddy_1.2.1_x64_en-US.msi" /L*V "Overbuddy.log"
```

When the installation fails, you'll find `Overbuddy.log` in the same folder. Please review it for any sensitive information. You can upload the log to a service like [pastebin](https://pastebin.com/) and share the link here.

Thanks for your help!

**Comment by KirillTregubov** [comment]
> [!IMPORTANT]
> Update on the situation: I seem to have resolved this issue in the [latest version of OverBuddy](https://github.com/KirillTregubov/OverBuddy/releases/latest). Please try it and let me know if it worked!

**Comment by KirillTregubov** [comment]
Closing, as it's been over a month since this issue has been resolved. If you are still encountering this, please [open a new issue](https://github.com/KirillTregubov/OverBuddy/issues/new).
