### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by annavpolonskaya** [KirillTregubov/OverBuddy#8]
Hello! I am unsure if this issue is just one that is happening to me right now, but upon trying to download OverBuddy, I'm able to go through the wizard, but once I get to the final page to download, I get the popup that I attached below. Is there any way to fix it? When I looked on Google, it said something about an outdated installer, but I'm not sure if that is something to do with my system or with the actual installer for OverBuddy. 

Thanks so much!

![image](https://github.com/user-attachments/assets/5993c84b-1c9b-4a82-8b85-c956ea1632dc)

**Comment by KirillTregubov** [comment]
Hi Anna!

I'm sorry you weren't able to install OverBuddy 😔. There's another open issue with users running into the same issue.

I have released a new version of OverBuddy which you can (download here)[https://github.com/KirillTregubov/OverBuddy/releases/tag/v1.3.0].

If you're comfortable with running commands, you can help debug by sharing a log of the installation process. This will help me diagnose the issue further. 
Please run the following command inside your Downloads folder (or wherever the installer is located), making sure the installer filename matches:
```cmd
msiexec /i "OverBuddy_1.3.0_x64_en-US.msi" /L*V "Overbuddy.log"
```

When the installation fails, you'll find `Overbuddy.log` in the same folder. Please review it for any sensitive information. You can upload the log to a service like [pastebin](https://pastebin.com/) and share the link here or email it to me (it's on my profile).

Thanks for your help!

**Comment by ItsXylium** [comment]
> Hi Anna!
> 
> I'm sorry you weren't able to install OverBuddy 😔. There's another open issue with users running into the same issue.
> 
> I have released a new version of OverBuddy which you can [download here](https://github.com/KirillTregubov/OverBuddy/releases/tag/v1.3.0).
> 
> If you're comfortable with running commands, you can help debug by sharing a log of the installation process. This will help me diagnose the issue further. Please run the following command inside your Downloads folder (or wherever the installer is located), making sure the installer filename matches:
> 
> ```batchfile
> msiexec /i "OverBuddy_1.3.0_x64_en-US.msi" /L*V "Overbuddy.log"
> ```
> 
> When the installation fails, you'll find `Overbuddy.log` in the same folder. Please review it for any sensitive information. You can upload the log to a service like [pastebin](https://pastebin.com/) and share the link here or email it to me (it's on my profile).
> 
> Thanks for your help!

I've been having this same problem as well, got the [pastebin](https://pastebin.com/dsmU2fNJ) of what it gave me. Hope it helps, would love to try this out without having installation issues :)

**Comment by KirillTregubov** [comment]
Hi @ItsXylium!

> > Hi Anna!
> > I'm sorry you weren't able to install OverBuddy 😔. There's another open issue with users running into the same issue.
> > I have released a new version of OverBuddy which you can [download here](https://github.com/KirillTregubov/OverBuddy/releases/tag/v1.3.0).
> > If you're comfortable with running commands, you can help debug by sharing a log of the installation process. This will help me diagnose the issue further. Please run the following command inside your Downloads folder (or wherever the installer is located), making sure the installer filename matches:
> > ```batchfile
> > msiexec /i "OverBuddy_1.3.0_x64_en-US.msi" /L*V "Overbuddy.log"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When the installation fails, you'll find `Overbuddy.log` in the same folder. Please review it for any sensitive information. You can upload the log to a service like [pastebin](https://pastebin.com/) and share the link here or email it to me (it's on my profile).
> > Thanks for your help!
> 
> I've been having this same problem as well, got the [pastebin](https://pastebin.com/dsmU2fNJ) of what it gave me. Hope it helps, would love to try this out without having installation issues :)

Thank you so much for your installation log @ItsXylium! Can you try to install this [potentially fixed version](https://github.com/KirillTregubov/OverBuddy/releases/download/pre-v1.3.1/OverBuddy_1.3.1_x64_en-US.msi)?

**Comment by ItsXylium** [comment]
> Hi @ItsXylium!
> 
> > > Hi Anna!
> > > I'm sorry you weren't able to install OverBuddy 😔. There's another open issue with users running into the same issue.
> > > I have released a new version of OverBuddy which you can [download here](https://github.com/KirillTregubov/OverBuddy/releases/tag/v1.3.0).
> > > If you're comfortable with running commands, you can help debug by sharing a log of the installation process. This will help me diagnose the issue further. Please run the following command inside your Downloads folder (or wherever the installer is located), making sure the installer filename matches:
> > > ```batchfile
> > > msiexec /i "OverBuddy_1.3.0_x64_en-US.msi" /L*V "Overbuddy.log"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > When the installation fails, you'll find `Overbuddy.log` in the same folder. Please review it for any sensitive information. You can upload the log to a service like [pastebin](https://pastebin.com/) and share the link here or email it to me (it's on my profile).
> > > Thanks for your help!
> > 
> > 
> > I've been having this same problem as well, got the [pastebin](https://pastebin.com/dsmU2fNJ) of what it gave me. Hope it helps, would love to try this out without having installation issues :)
> 
> Thank you so much for your installation log! Can you try to install this [potentially fixed version](https://github.com/KirillTregubov/OverBuddy/releases/download/pre-v1.3.1/OverBuddy_1.3.1_x64_en-US.msi)?

That version has indeed fixed my problem @KirillTregubov

**Comment by KirillTregubov** [comment]
> > Hi @ItsXylium!
> > > > Hi Anna!
> > > > I'm sorry you weren't able to install OverBuddy 😔. There's another open issue with users running into the same issue.
> > > > I have released a new version of OverBuddy which you can [download here](https://github.com/KirillTregubov/OverBuddy/releases/tag/v1.3.0).
> > > > If you're comfortable with running commands, you can help debug by sharing a log of the installation process. This will help me diagnose the issue further. Please run the following command inside your Downloads folder (or wherever the installer is located), making sure the installer filename matches:
> > > > ```batchfile
> > > > msiexec /i "OverBuddy_1.3.0_x64_en-US.msi" /L*V "Overbuddy.log"
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > When the installation fails, you'll find `Overbuddy.log` in the same folder. Please review it for any sensitive information. You can upload the log to a service like [pastebin](https://pastebin.com/) and share the link here or email it to me (it's on my profile).
> > > > Thanks for your help!
> > > 
> > > 
> > > I've been having this same problem as well, got the [pastebin](https://pastebin.com/dsmU2fNJ) of what it gave me. Hope it helps, would love to try this out without having installation issues :)
> > 
> > 
> > Thank you so much for your installation log! Can you try to install this [potentially fixed version](https://github.com/KirillTregubov/OverBuddy/releases/download/pre-v1.3.1/OverBuddy_1.3.1_x64_en-US.msi)?
> 
> That version has indeed fixed my problem @KirillTregubov

Thank you so much for your help fixing this for everybody else!!

If you have any comments about the app, suggestions or criticism, do not hesistate to reach out! And if you like it, I would really appreciate you sharing it with your friends 😄!

**Comment by ItsXylium** [comment]
> If you have any comments about the app, suggestions or criticism, do not hesistate to reach out! And if you like it, I would really appreciate you sharing it with your friends 😄!

glad to be of help, your app seemed very interesting to use and was confused as to why it wasn't working. but i'm glad that problem is fixed now! 😄

**Comment by KirillTregubov** [comment]
Closing, as it's been over a month since this issue has been reported as resolved. If you are still encountering this, please [open a new issue](https://github.com/KirillTregubov/OverBuddy/issues/new).
